[package]
name = "circuits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ec = "0.4.2"
ark-ff = "0.4.2"
ark-secp256k1 = "0.4.0"
ark-secq256k1 = "0.4.0"
ark-std = "0.4.0"
ethers = "2.0.10"
num-bigint = "0.4.4"
spartan = { path = "../../../spartan-evm" }
